In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
dataset = pd.read_csv('insurance.csv')

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['sex'] = le.fit_transform(dataset['sex'])
dataset['smoker'] = le.fit_transform(dataset['smoker'])

In [ ]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[[19 0 27.9 0 1 'southwest']
 [18 1 33.77 1 0 'southeast']
 [28 1 33.0 3 0 'southeast']
 ...
 [18 0 36.85 0 0 'southeast']
 [21 0 25.8 0 0 'southwest']
 [61 0 29.07 0 1 'northwest']]


In [ ]:
print(y)

[16884.924   1725.5523  4449.462  ...  1629.8335  2007.945  29141.3603]


In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [5])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 0.0 0.0 ... 27.9 0 1]
 [0.0 0.0 1.0 ... 33.77 1 0]
 [0.0 0.0 1.0 ... 33.0 3 0]
 ...
 [0.0 0.0 1.0 ... 36.85 0 0]
 [0.0 0.0 0.0 ... 25.8 0 0]
 [0.0 1.0 0.0 ... 29.07 0 1]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [ ]:
print(y_test)

[ 9724.53  8547.69 45702.02 12950.07  9644.25  4500.34  2198.19 11436.74
  7537.16  5425.02  6753.04 10493.95  7337.75  4185.1  18310.74 10702.64
 12523.6   3490.55  6457.84 33475.82 23967.38 12643.38 23045.57 23065.42
  1674.63  4667.61  3732.63  7682.67  3756.62  8413.46  8059.68 48970.25
 12979.36 20630.28 14571.89  4137.52  8347.16 51194.56 40003.33  1880.49
  5458.05  2867.12 20149.32 47496.49 36149.48 26018.95 19749.38  6940.91
  4718.2  22192.44  2899.49 18838.7  23568.27 46255.11 24227.34  3268.85
  2322.62  8827.21 14478.33 13112.6   1253.94 46718.16 13919.82  9630.4
 10736.87  9880.07 32548.34 38746.36  3180.51  8162.72 13041.92 11554.22
 16232.85 13887.97 13012.21 13217.09  7147.1   7731.43 20296.86 47403.88
 11658.38 45863.21  2055.32  7441.05 41034.22 18972.49  3410.32  2699.57
 12333.83 36837.47  6334.34 10214.64 17878.9   8515.76  4518.83  5148.55
 42303.69 38998.55  5327.4  10602.39  1824.29  5377.46  4349.46 37742.58
 32787.46  3353.47 10577.09  3556.92 11944.59 52590.

In [ ]:
from xgboost import XGBRegressor
regressor = XGBRegressor()
regressor.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [ ]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[10585.88  9724.53]
 [ 8282.31  8547.69]
 [46487.27 45702.02]
 [10929.33 12950.07]
 [11518.08  9644.25]
 [ 8114.92  4500.34]
 [ 1399.49  2198.19]
 [ 9207.52 11436.74]
 [ 5971.12  7537.16]
 [ 4988.98  5425.02]
 [ 6615.66  6753.04]
 [23439.74 10493.95]
 [ 7465.45  7337.75]
 [ 9093.59  4185.1 ]
 [27230.73 18310.74]
 [13711.9  10702.64]
 [12800.34 12523.6 ]
 [ 7086.58  3490.55]
 [ 6313.09  6457.84]
 [33247.07 33475.82]
 [22732.51 23967.38]
 [15228.89 12643.38]
 [10019.44 23045.57]
 [28521.25 23065.42]
 [ 5285.5   1674.63]
 [11874.42  4667.61]
 [ 4387.56  3732.63]
 [ 7459.13  7682.67]
 [ 3521.16  3756.62]
 [ 7853.65  8413.46]
 [ 7110.48  8059.68]
 [49526.66 48970.25]
 [14667.66 12979.36]
 [11499.51 20630.28]
 [16267.89 14571.89]
 [ 3422.45  4137.52]
 [ 8125.39  8347.16]
 [35999.3  51194.56]
 [38731.97 40003.33]
 [ 1288.43  1880.49]
 [ 7912.31  5458.05]
 [ 3454.22  2867.12]
 [19625.35 20149.32]
 [49623.5  47496.49]
 [34621.77 36149.48]
 [ 4130.53 26018.95]
 [14635.79 19749.38]
 [ 6491.31  6

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8463656618285185